language: node_js
node_js:
- '6.9'
sudo: required
services:
  - docker
git:
  submodules: true
before_script:
  - docker-compose up -d server
script:
  - ./run.build.sh
  - ./run.tests.sh
after_script:
  - docker-compose down
after_success:
  - ./build.sh
  - docker login -u="gurgul.grzegorz@gmail.com" -e="gurgul.grzegorz@gmail.com" -p="85c2a94d-47f7-4139-b98c-8a357ab9d129" registry.heroku.com
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker tag justmarried/jmserver:production-latest registry.heroku.com/just-married-server
      docker push registry.heroku.com/just-married-server;
    else
      docker tag justmarried/jmserver:production-latest registry.heroku.com/just-married-sta-server
      docker push registry.heroku.com/just-married-sta-server;
    fi
branches:
  only:
  - master
  - develop
