language: node_js
node_js:
- '6.9'
sudo: required
services:
  - docker
git:
  submodules: true
before_script:
  - docker-compose up -d server
script:
  - ./run.build.sh
  - ./run.tests.sh
after_script:
  - docker-compose down
after_success:
  - ./build.sh
  - docker login -u AWS -p ${AWS_DOCKER_REPO_PASSWORD} -e none https://585734593719.dkr.ecr.eu-central-1.amazonaws.com
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker tag just-married/jmserver:production-latest 585734593719.dkr.ecr.eu-central-1.amazonaws.com/just-married/jmserver:latest;
      docker push 585734593719.dkr.ecr.eu-central-1.amazonaws.com/just-married/jmserver:latest;
    else
      echo "Doing nothing for now";
    fi
branches:
  only:
  - master
  - develop
