language: node_js
node_js:
- '6.9'
sudo: required
services:
  - docker
git:
  submodules: true
before_script:
  - docker-compose up -d server
script:
  - ./run.build.sh
  - ./run.tests.sh
after_script:
  - docker-compose down
after_success:
  - ./build.sh
  - docker login -u ${DOCKER_REGISTRY_USERNAME} -p ${DOCKER_REGISTRY_PASSWORD}
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker tag just-married/jmserver:production-latest justmarried/just-married-server:latest;
      docker push justmarried/just-married-server:latest;
    else
      echo "Doing nothing for now";
    fi
  - docker logout
branches:
  only:
  - master
  - develop
