swagger: '2.0'
basePath: /api
info:
  version: "1.0.0"
  title: JustMarried API

paths:

  /auth/token:
      get:
        description: |
          Returns a new authentication token for an authorized user.

  /auth/local:
      post:
        description: |
          Authenticates a user locally using login and password
          returning a valid token if authenticated positively.
        parameters:
          - name: login
            in: body
            required: true
            type: string
          - name: password
            in: body
            required: true
            type: string

  /auth/facebook:
      get:
        description: |
          Tries to get a authentication response from Facebook
          resulting in returning a response with authentication token.

  /auth/facebook/callback:
      get:
        description: |
          Internal authentication callback to use for Facebook when authentity is verified.

  /users:
    post:
      description: |
        Creates a new `User`.
      parameters:
        - name: login
          in: body
          required: true
          type: string
        - name: password
          in: body
          required: true
          type: string

  /users/{userId}:
    get:
      description: |
        Gets a `User` by `userId`
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            title: User
            type: object