swagger: '2.0'
basePath: /api
info:
  version: "1.0.0"
  title: JustMarried API

paths:

  /auth/token:
      get:
        description: |
          Returns a new authentication token for an authorized user.
        responses:
          200:
              description: Successful response
              schema:
                $ref: '#/definitions/User'

  /auth/local:
      post:
        description: |
          Authenticates a user locally using login and password
          returning a valid token if authenticated positively.
        parameters:
          - name: credentials
            in: body
            description: Credentials to use in login attempt.
            required: true
            schema:
              $ref: '#/definitions/Credentials'
        responses:
          200:
              description: Successful response
              schema:
                $ref: '#/definitions/User'

  /auth/facebook:
      get:
        description: |
          Tries to get a authentication response from Facebook
          resulting in returning a response with authentication token.
        responses:
          200:
              description: Successful response

  /auth/facebook/callback:
      get:
        description: |
          Authentication callback to use for Facebook when authentity is verified.
        responses:
          200:
              description: Successful response
              schema:
                $ref: '#/definitions/User'


  /users/{userId}:
    get:
      description: |
        Gets a `User` by `userId`
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            title: User
            type: object


definitions:

  Credentials:
    required:
      - login
      - password
    properties:
      login:
        type: string
      password:
        type: string

  User:
    required:
      - login
      - password
    properties:
      login:
        type: string
      password:
        type: string
