swagger: '2.0'
basePath: /api
schemes:
  - http
info:
  version: "1.0.0"
  title: JustMarried API

securityDefinitions:
  bearer:
    type: apiKey
    name: token
    in: header

paths:

  /ping:
      get:
        description: |
          An easiest call to the server.
        responses:
          200:
              description: Successfully communicated with the server.


  /auth/token:
      get:
        description: |
          Returns a new authentication token for an authorized user.
        security:
          - bearer: []
        responses:
          200:
              description: Account with token to use in the header
              schema:
                $ref: '#/definitions/Account'

  /auth/local:
      post:
        description: |
          Authenticates a user locally using login and password
          returning a valid token if authenticated positively.
        parameters:
          - name: credentials
            in: body
            description: Credentials to use in login attempt.
            required: true
            schema:
              $ref: '#/definitions/Credentials'
        responses:
          200:
              description: Account with token to use in the header
              schema:
                $ref: '#/definitions/Account'

  /auth/facebook.authentication:
      get:
        description: |
          Tries to get a authentication response from Facebook
          resulting in returning a response with authentication token.
        responses:
          200:
              description: Successful response

  /auth/facebook.authorization:
    get:
      security:
          - bearer: []
      description: |
        Tries to get a authorization response from Facebook
        resulting in merging facebook account details into user account.
      responses:
        200:
            description: Successful response

  /auth/facebook/callback:
      get:
        description: |
          Authentication callback to use for Facebook when authentity is verified.
        responses:
          200:
              description: Account with token to use in the header
              schema:
                $ref: '#/definitions/Account'

  /auth/google.authentication:
      get:
        description: |
          Tries to get a authentication response from Google
          resulting in returning a response with authentication token.
        responses:
          200:
              description: Successful response

  /auth/google.authorization:
    get:
      security:
          - bearer: []
      description: |
        Tries to get a authorization response from Google
        resulting in merging facebook account details into user account.
      responses:
        200:
            description: Successful response

  /auth/google/callback:
      get:
        description: |
          Authentication callback to use for Google when authentity is verified.
        responses:
          200:
              description: Account with token to use in the header
              schema:
                $ref: '#/definitions/Account'

  /accounts:
    post:
      description: |
        Creates a new local account
      parameters:
        - name: account
          in: body
          required: true
          schema:
            $ref: '#/definitions/Account'
      responses:
          200:
              description: Newly created account with token to use in the header
              schema:
                $ref: '#/definitions/Account'

  /users:
    get:
      description: |
        Lists users relevant for current user using given criteria
      security:
          - bearer: []
      parameters:
          - name: limit
            in: query
            type: string
          - name: offset
            in: query
            type: string
          - name: sortBy
            in: query
            type: string
          - name: role
            in: query
            type: string
      responses:
        200:
          description: List of `Users` matching the criteria specified
          schema:
            $ref: '#/definitions/Users'
    post:
        description: |
          Creates a new user - might be bound to account sometime later
        security:
          - bearer: []
        parameters:
          - name: user
            in: body
            description: User to save
            required: true
            schema:
              $ref: '#/definitions/User'
        responses:
          200:
              description: The newly created user
              schema:
                $ref: '#/definitions/User'

  /users/{userId}:
    get:
      description: |
        Gets a `User` by `userId`
      security:
          - bearer: []
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      responses:
        200:
          description: User with given `userId`
          schema:
            $ref: '#/definitions/User'
    put:
      description: |
        Modifies a particular `User`
      security:
        - bearer: []
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: user
          in: body
          description: User details to update
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
            description: The newly created user
            schema:
              $ref: '#/definitions/User'

  /wedding:
    get:
       description: |
        Gets a wedding.
       security:
          - bearer: []
       responses:
        200:
          description: A wedding of currently logged user
          schema:
            $ref: '#/definitions/Wedding'


  /tasks:
    get:
      description: |
        Gets list of `Task`s matching given query parameters.
      security:
          - bearer: []
      parameters:
        - name: limit
          in: query
          type: string
        - name: offset
          in: query
          type: string
        - name: sortBy
          in: query
          type: string
        - name: state
          in: query
          type: string
      responses:
        200:
          description: List of `Task`s matching the criteria specified
          schema:
            $ref: '#/definitions/Tasks'

    post:
      description: |
        Creates a new `Task`
      security:
        - bearer: []
      parameters:
        - name: task
          in: body
          required: true
          schema:
            $ref: '#/definitions/Task'
      responses:
        200:
          description: The newly created `Task`
          schema:
            $ref: '#/definitions/Task'


definitions:

  Credentials:
    required:
      - login
      - password
    properties:
      login:
        type: string
      password:
        type: string

  Account:
    required:
      - login
      - password
    properties:
      login:
        type: string
      password:
        type: string

  User:
    properties:
      _id:
        type: integer
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      actors:
        type: array
        items:
          - $ref: '#/definitions/User'

  Task:
    properties:
      name:
        type: string
      status:
        type: string
      description:
        type: string
      owners:
        type: array
        items:
          - $ref: '#/definitions/User'

  Wedding:
    properties:
      _id:
        type: integer
      participants:
        type: object
      guests:
        type: array
        items:
          - $ref: '#/definitions/User'

  Users:
    type: array
    items:
      - $ref: '#/definitions/User'

  Tasks:
    type: array
    items:
      - $ref: '#/definitions/Task'

